### ISSUE TITLE
pycuda.driver error

### ISSUE THREAD

**Issue by YuyaKiguchi** [swarris/Pacasus#10]
Hi,

I run the pacasus for my WGA long reads.
This is the command.
> pacasus.py test.fasta -o test.pacasus --device_type=CPU -L test.pacasus.log

But I got the python module error of pycuda.driver.

Please check the log file, and suggest the solution.

[test.pacasus.log](https://github.com/swarris/Pacasus/files/3271715/test.pacasus.log)

Best,
Yuya.

**Comment by swarris** [comment]
Hi,

Did you install [pycuda?](https://documen.tician.de/pycuda/)? 
And you appear to be running pacasus on a CPU. In that case you need OpenCL en pyopencl.

Best,
Sven

**Comment by YuyaKiguchi** [comment]
Thanks for reply.

I rerun using CPU and OpenCL options.
> pacasus.py KG-V-spike1-EQ.rm_ctrl_hg.400k.correctedReads.fasta --device_type=CPU --framework=opencl -o test.fasta -L test.log

But I got the another error. 
[test.log](https://github.com/swarris/Pacasus/files/3274364/test.log)

Please suggest the solution.

Best,
Yuya.

**Comment by YuyaKiguchi** [comment]
Thanks for reply.

I rerun using CPU and OpenCL options.
> pacasus.py test.fasta --device_type=CPU --framework=opencl -o test.opencl -L test.log

But I got the another error. 
[test.log](https://github.com/swarris/Pacasus/files/3274381/test.log)

Please suggest the solution.

Best,
Yuya.

**Comment by swarris** [comment]
Hi,

You are (still) missing the OpenCL drivers or they are not properly installed. Please check out the [readme](https://github.com/swarris/Pacasus) for more information.

Best,
Sven
