### ISSUE TITLE
ConfigParser and Python 3?

### ISSUE THREAD

**Issue by baraaorabi** [swarris/Pacasus#12]
Running with Python 3 is failing because of:
```
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
``` 
and the [here](https://docs.python.org/2/library/configparser.html):

> **Note**: The `ConfigParser` module has been renamed to `configparser` in Python 3. The [2to3 ](https://docs.python.org/2/glossary.html#term-2to3) tool will automatically adapt imports when converting your sources to Python 3.

**Comment by baraaorabi** [comment]
Maybe adding a note about not using Python 3 to README would be helpful?

**Comment by swarris** [comment]
Thanks for the comment. I will fix this asap. The underlying pyPaSWAS already works with python 3.
