### ISSUE TITLE
Fastq input seems to cause a silent failure

### ISSUE THREAD

**Issue by rsharris** [swarris/Pacasus#18]
(Issue 17 gives details about my machine setup.)

My first attempt at using pacasus, I gave it fastq input. It isn't clear from the output, but I eventually concluded that fastq input is not supported AND the program seems to just sort of fail silently.

First, is my conclusion correct?

Second, if that is correct, it would be an improvement if the program verified that its input conformed to whatever format it expects. Especially for a tool that operates on pacbio reads -- most people are going to have these as fastq. While it's easy enough to covert them to fasta, there's very little (if anything) in the pacasus documentation that would make the user expect she needs to do that conversion.

**Comment by swarris** [comment]
Your conclusion that it will try to parse the fastq as a fasta file is correct. The Biopython library indeed will give no errors and you end up with zero reads to be processed. 
The readme and the command line help will inform you that:

-1 | --filetype1 | File type of the first input file. See bioPython IO for available options. Default fasta
-- | -- | --

the default input type is fasta. Fastq is not a problem, just add -1 fastq to the command line arguments and you are ready to go. For all other supported file formats, please check the [biopython documentation](https://biopython.org/DIST/docs/api/Bio.SeqIO-module.html) (as there are numerous supported file formats)
