### ISSUE TITLE
TypeError: sequence item 0: expected string, pyopencl._cl._ErrorRecord found

### ISSUE THREAD

**Issue by peterdfields** [swarris/Pacasus#8]
Hi @swarris 

I tried to get pacasus setup on a couple additional machines to distribute the larger dataset across more resources. I'm using the following command to execute Pacasus:

`python ~/bioinformatics/Pacasus/pacasus.py --loglevel=info some.fasta --device_type=CPU --platform_name=Intel --framework=opencl -o cleaned.fasta --limit_length=20000 --filter_factor=0.00001 --query_coverage=0.0001 --query_identity=0.0001 --relative_score=0.0001 --base_score=0.25`

and I immediately see the following error:

`INFO - Initializing application...
INFO - Application initialized.
INFO - Setting program...
INFO - No gap extension penalty detected: using original PaSWAS scoring algorithm
Traceback (most recent call last):
  File "/home/peter/bioinformatics/Pacasus/pacasus.py", line 21, in <module>
    print('Program ended. The message was: ' + ','.join(exception.args))
TypeError: sequence item 0: expected string, pyopencl._cl._ErrorRecord found`

I'm only seeing this error on new builds of the software rather than any machine I previously installed the software on. I wondered if the updates made to deal with the previous [issue #7](https://github.com/swarris/Pacasus/issues/7) could be causing this problem? Please let me know if any additional information about the machines would be useful to determine what's going wrong.

**Comment by swarris** [comment]
I changed the code a little so it prints the entire exception. This should provide more information.
 
Could you set loglevel to debug? 

I have no difficulty running a data set with your command line:
```bash
python pacasus.py --loglevel=debug /data/reads_15000.fasta --device_type=CPU --platform_name=Intel --framework=opencl -o cleaned.fasta --limit_length=20000 --filter_factor=0.00001 --query_coverage=0.0001 --query_identity=0.0001 --relative_score=0.0001 --base_score=0.25 -L log.txt &
```
The log.txt contains entries like:
```bash
2019-01-07 23:53:09,379 - INFO - No gap extension penalty detected: using original PaSWAS scoring algorithm
2019-01-07 23:53:09,382 - DEBUG - Found platform <pyopencl.Platform 'Intel(R) CPU Runtime for OpenCL(TM) Applications' at 0x56286127f400>
2019-01-07 23:53:09,382 - DEBUG - Initializing device 0
```
and:
```bash
2019-01-08 00:05:02,163 - DEBUG - build program: start building program from source on <pyopencl.Device 'Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz' on 'Intel(R) CPU Runtime for OpenCL(TM) Applications' at 0x55cc155d3b18>
```
